apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pictshare-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: pictshare
    app.kubernetes.io/environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/kubernetes-devops-platform.git
    targetRevision: HEAD
    path: charts/pictshare
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pictshare-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10