apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solemate-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/kubernetes-devops-platform.git
    targetRevision: HEAD
    path: charts/solemate-frontend
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: solemate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true