apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "solemate-backend.fullname" . }}
  labels:
    {{- include "solemate-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "solemate-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "solemate-backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: PORT
              value: {{ .Values.app.port | quote }}
            - name: NODE_ENV
              value: {{ .Values.app.nodeEnv | quote }}
            - name: DATABASE_URL
              value: {{ .Values.database.url | quote }}
            - name: JWT_SECRET
              value: {{ .Values.app.jwtSecret | quote }}
            - name: JWT_EXPIRES_IN
              value: {{ .Values.app.jwtExpiresIn | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}