apiVersion: v2
name: solemate-frontend
description: SoleMate E-commerce Frontend Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ecommerce
  - frontend
  - nextjs
  - react
home: https://github.com/solemate/frontend
maintainers:
  - name: SoleMate Team
    email: dev@solemate.com